baseURL = "https://blog.ad-am.dev"
languageCode = "en-us"
title = "Adam's Blog!"
theme = "hugo-nes-classic-dema"

[menu]

  [[menu.main]]
    identifier = "back"
    name = "Main Site"
    url = "https://ad-am.dev"
    weight = 10
  [[menu.main]]
    identifier = "home"
    name = "Blog Home"
    url = "https://blog.ad-am.dev"
    weight = 10
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
disableInlineCSS = true
