baseURL = "https://dabuadas.netlify.com"
languageCode = "en-us"
title = "Dema's Blog!"
theme = "hugo-nes-classic-dema"

[menu]

  [[menu.main]]
    identifier = "back"
    name = "Back"
    url = "https://dabuadas.me"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
disableInlineCSS = true
